### ISSUE TITLE
NRE when writing an attribute before adding a reference to NUnit

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit.analyzers#28]
The following code makes the analyzer throw NRE if one has not added a reference to NUnit.

```csharp
[TestFixture]
public class Class1
{
    [Test]
    public void Test1()
    {
    }
}
```

The method should probably just return if `testCaseType` is `null`.

Exception 
```
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=nunit.analyzers
  StackTrace:
       at NUnit.Analyzers.TestCaseUsage.TestCaseUsageAnalyzer.AnalyzeAttribute(SyntaxNodeAnalysisContext context) in F:\TEMP\Github\nunit.analyzers\src\nunit.analyzers\TestCaseUsage\TestCaseUsageAnalyzer.cs:line 53
       at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
       at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
  InnerException: 
```

**Comment by mikkelbu** [comment]
Closed with 741196c.
