### ISSUE TITLE
TestCaseUsageAnalyzer throws NullReferenceException for non-existent attribute

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit.analyzers#8]
The TestCaseUsageAnalyzer throws a NullReferenceException for any attribute which doesn't exist. I found this out as I stopped for long enough through the word `TestCase` for the analyzer to kick in and try and find a `TestC` attribute! 

I'm not sure this 'breaks' anything as such, but it does fill up my errors window. Unfortunately, the warnings don't clear once you type the rest of the attribute. 👎 This is VS2015 Update 3.

Repro:

```
using System;
using NUnit.Framework;

namespace UnitTestProject1
{
    [TestFixture]
    public class UnitTest1
    {
        [TestC]
        public void TestMethod1(string hey, double left)
        {
        }
    }
}
```

StackTrace:
```
Warning	AD0001	Analyzer 'NUnit.Analyzers.TestCaseUsage.TestCaseUsageAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	UnitTestProject1		1	Active	Analyzer 'NUnit.Analyzers.TestCaseUsage.TestCaseUsageAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: UnitTestProject1
SyntaxTree: c:\Users\Chris\Documents\Visual Studio 2015\Projects\UnitTestProject1\UnitTestProject1\UnitTest1.cs
SyntaxNode: TestC [AttributeSyntax]@[135..140) (8,9)-(8,14)

System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.Analyzers.TestCaseUsage.TestCaseUsageAnalyzer.AnalyzeAttribute(SyntaxNodeAnalysisContext context) in C:\Users\Chris\Documents\git\nunit.analyzers\src\nunit.analyzers\TestCaseUsage\TestCaseUsageAnalyzer.cs:line 53
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

**Comment by ChrisMaddock** [comment]
Just found I have the same issue with the ClassicModelAssertUsageAnalyzer - e.g. for `Assert.AreEqual("hey");` and `Assert.AreEqual("hey", MyHalfFinishedStrin);``.  I assume they're the same fix if not same issue, here's a sample stacktrace for the other.

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'NUnit.Analyzers.ClassicModelAssertUsage.ClassicModelAssertUsageAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	UnitTestProject1		1	Active	Analyzer 'NUnit.Analyzers.ClassicModelAssertUsage.ClassicModelAssertUsageAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: UnitTestProject1
SyntaxTree: c:\Users\Chris\Documents\Visual Studio 2015\Projects\UnitTestProject1\UnitTestProject1\UnitTest1.cs
SyntaxNode: Assert.AreEqual("hey") [InvocationExpressionSyntax]@[223..245) (11,12)-(11,34)

System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.Analyzers.ClassicModelAssertUsage.ClassicModelAssertUsageAnalyzer.AnalyzeInvocation(SyntaxNodeAnalysisContext context) in C:\Users\Chris\Documents\git\nunit.analyzers\src\nunit.analyzers\ClassicModelAssertUsage\ClassicModelAssertUsageAnalyzer.cs:line 56
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

**Comment by JasonBock** [comment]
OK, I'll take a look at them.
